### PR TITLE
Unify benchmark tool based on stresscli library

### PR DESCRIPTION
**Pull request by lvliang-intel**
## Description

Unify benchmark tool based on stresscli library

## Issues

`n/a`

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

None

## Tests

Local test.

### CODE REVIEW

**Comment by daisy-ycguo** [comment]
Thank you for the issue @lvliang-intel. Does the usage guidance in README need to be changed accordingly?

**Comment by gavinlichn** [comment]
Great work @lvliang-intel ! 

So the file [stress_benchmark.py](https://github.com/opea-project/GenAIEval/blob/main/evals/benchmark/stress_benchmark.py) can be removed also?

**Comment by lvliang-intel** [comment]
> Thank you for the issue @lvliang-intel. Does the usage guidance in README need to be changed accordingly?

Yes, README updated.

**Comment by lvliang-intel** [comment]
> Great work @lvliang-intel !
> 
> So the file [stress_benchmark.py](https://github.com/opea-project/GenAIEval/blob/main/evals/benchmark/stress_benchmark.py) can be removed also?

removed.

**Review by letonghan — APPROVED** [review]

**Pull request merged**
