### PR TITLE
Minimize requirements for user data for OPEA ragas

### PR DESCRIPTION
**Pull request by adkakne**
## Description

Purpose of this PR to minimize requirements on user data and improve flexibility and coverage of use-cases. 

Prior to this PR, we required all 4 fields (question, answer, ground truth and contexts). But, this PR ensures we only require minimum input fields for a given list of metrics. E.g., "faithfulness" does not require ground _truth field, so it will not be asked from the user. 

This PR grabs list of required fields for each metric from ragas and sets their union as the final required fields for a given list of metrics. We use this final list of required fields to be present in input data. 

## Issues

`n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Dependencies

None. 

## Tests

This PR was tested for OpenAI (ragas uses GPT-4o by default) and HF endpoint (Llama 3.1 70b on Gaudi2 machine).

### CODE REVIEW

**Comment by adkakne** [comment]
Hi @XinyuYe-Intel, 

Traceback is - 
`Traceback (most recent call last):
  File "/GenAIEval/tests/test_ragas.py", line 39, in test_ragas
    metric.measure(test_case)
  File "/usr/local/lib/python3.10/dist-packages/evals/metrics/ragas/ragas.py", line 121, in measure
    for column in list(metric._required_columns.values())[0]:
AttributeError: 'AnswerRelevancy' object has no attribute '_required_columns'`

But `AnswerRelevancy` metric in ragas main branch has attribute `_required_columns` as seen here - https://github.com/explodinggradients/ragas/blob/main/src/ragas/metrics/_answer_relevance.py#L111. 

Are we using the same version of ragas in testing environment? Thank you.

**Comment by adkakne** [comment]
Hi @XinyuYe-Intel, the error is - "AttributeError: 'AnswerRelevancy' object has no attribute '_required_columns'". But, latest version of ragas has `_required_columns` for `AnswerRelevancy` metric as found here - https://github.com/explodinggradients/ragas/blob/main/src/ragas/metrics/_answer_relevance.py#L111. Please share your insights. Thank you.

**Review by minmin-intel — APPROVED** [review]
LGTM. Please make sure the unit test pass.

**Comment by lkk12014402** [comment]
LGTM. please make sure the ut https://github.com/opea-project/GenAIEval/blob/main/tests/test_ragas.py pass. you can test the ut locally.

**Review by XinyuYe-Intel — APPROVED** [review]

**Comment by adkakne** [comment]
Thank you for reviewing. The issue was coming from older versions of ragas. I added support for them and now the code passes all checks. Thanks!

**Pull request merged**
